[package]
name = "lrcshow-rs"
version = "0.1.1"
authors = ["Nikola Kocić <nikolakocic@gmail.com>"]
edition = "2018"

[dependencies]
dbus = "0.6.4"
notify = "4.0.12"
structopt = "0.2.18"
url = "1.7.2"
