[package]
name = "lrcshow-rs"
version = "0.3.0"
authors = ["Nikola Kocić <nikolakocic@gmail.com>"]
edition = "2018"

[dependencies]
dbus = "0.6.4"
log = "0.4.6"
notify = "4.0.12"
structopt = "0.2.18"
url = "1.7.2"

[dependencies.env_logger]
version = "0.6.2"
default-features = false
features = ["termcolor", "atty", "humantime"]
