[package]
name = "lrcshow-rs"
version = "0.5.0"
authors = ["Nikola Kocić <nikolakocic@gmail.com>"]
edition = "2018"

[dependencies]
dbus = "0.7.1"
log = "0.4.8"
notify = "4.0.15"
structopt = "0.3.14"
url = "2.1.1"

[dependencies.env_logger]
version = "0.8.4"
default-features = false
features = ["termcolor", "atty", "humantime"]
