name: "Verifications"

on:
  push:
  pull_request:

jobs:
  verifications:
    name: Code verifications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required tools
        run: apt update && apt install -y libdbus-1-dev pkg-config
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          cache: false
      - uses: actions-rust-lang/rustfmt@v1
        continue-on-error: true
      - name: Compile and run tests
        run: cargo test --all-features
      - run: cargo clippy
